arch: SegNet
batch_size: 1
dataset: dsb2018_96
deep_supervision: false
early_stopping: -1
epochs: 100
factor: 0.1
gamma: 0.6666666666666666
gradient_ext: .png
img_ext: .jpg
input_channels: 3
input_h: 512
input_w: 512
loss: BCEDiceLoss
lr: 0.0001
mask_ext: .png
milestones: '50'
min_lr: 1.0e-05
momentum: 0.9
name: dsb2018_96_SegNet_woDS
nesterov: false
num_classes: 1
num_workers: 0
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.001
